export const LOGIN = 'LOGIN'

export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SET_LOGIN_DETAILS = 'SET_LOGIN_DETAILS'

export const SET_USER_DETAILS = 'SET_USER_DETAILS'

export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN'

export const LOGOUT = 'LOGOUT'

export const SHOW_LOADER = 'SHOW_LOADER'

export const HIDE_LOADER = 'HIDE_LOADER'

export const SIGNUP = 'SIGNUP'

export const SET_SIGNUP_LOADER = 'SET_SIGNUP_LOADER'

export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR'

export const SET_SIGNUP_CREAD = 'SET_SIGNUP_CREAD'

export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'

export const SET_SIGUN_SUCCESS = 'SET_SIGNUP_SUCCESS'

export const SET_SIGNUP_USER = 'SET_SIGNUP_USER'

export const OTP_VERIFY = 'SET_OTP_VERIFY'

export const SET_OTP_LOADER = 'SET_OTP_LOADER'

export const SET_OTP_ERROR = 'SET_OTP_ERROR'

export const OTP_SUCCESS = 'OTP_SUCCESS'

export const RESEND_OTP = 'RESEND_OTP'

export const SET_RESEND_OTP_LOADER = 'SET_RESEND_OTP_LOADER'

export const RESEND_OTP_ERROR = 'RESEND_OTP_ERROR'

export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS'

export const RESET_PASSWORD = 'RESET_PASSWORD'

export const SET_RESET_PASSWORD_LOADER = 'SET_RESET_PASSWORD_LOADER'

export const SET_RESET_PASSWORD_SUCCESS = 'SET_RESET_PASSWORD_SUCCESS'

export const SET_RESET_PASSWORD_ERROR = 'SET_RESET_PASSWORD_ERROR'

export const FORGET_PASSWORD = 'FORGET_PASSWORD'

export const SET_FORGET_PASSWORD_LOADER = 'SET_FORGET_PASSWORD_LOADER'

export const SET_FORGET_PASSWORD_SUCCESS = 'SET_FORGET_PASSWORD_SUCCESS'

export const SET_FORGET_PASSWORD_ERROR = 'SET_FORGET_PASSWORD_ERROR'

export const SET_FORGET_PASSWORD_OTP_SUCCESS = 'SET_FORGET_PASSWORD_OTP_SUCCESS'

export const MOBILE_NUMBER__REQUEST = 'MOBILE_NUMBER__REQUEST'

export const SET_MOBILE_NUMBER_LOADER = 'SET_MOBILE_NUMBER_LOADER'

export const SET_MOBILE_NUMBER_SUCCESS = 'SET_MOBILE_NUMBER_SUCCESS'

export const SET_MOBILE_NUMBER_ERROR = 'SET_MOBILE_NUMBER_ERROR'

export const SET_MOBILE_NUMBER_OTP_SUCCESS = 'SET_MOBILE_NUMBER_OTP_SUCCESS'

export const MOBILE_OTP_VERIFY = 'SET_MOBILE_OTP_VERIFY'

export const SET_MOBILE_OTP_LOADER = 'SET_MOBILE_OTP_LOADER'

export const SET_MOBILE_OTP_ERROR = 'SET_MOBILE_OTP_ERROR'

export const MOBILE_OTP_SUCCESS = 'MOBILE_OTP_SUCCESS'

export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE'

export const COUNTRY_LIST = 'COUNTRY_LIST'

export const SET_COUNTRY_LIST_LOADER = 'SET_COUNTRY_LIST_LOADER'

export const SET_COUNTRY_LIST_ERROR = 'SET_COUNTRY_LIST_ERROR'

export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS'

export const SET_LOGIN_CREAD = 'SET_LOGIN_CREAD'
