export const GET_BANKS = 'GET_BANKS'

export const SET_GET_BANK_LOADER = 'SET_GET_BANK_LOADER'

export const SET_GET_BANK_ERROR = 'SET_GET_BANK_ERROR'

export const GET_BANK_SUCCESS = 'GET_BANK_SUCCESS'

export const ADD_BANK = 'ADD_BANK'

export const SET_ADD_BANK_LOADER = 'SET_ADD_BANK_LOADER'

export const SET_ADD_BANK_ERROR = 'SET_ADD_BANK_ERROR'

export const ADD_BANK_SUCCESS = 'ADD_BANK_SUCCESS'

export const ACCOUNT_VERIFY = 'ACCOUNT_VERIFY'


export const WITHDRAW_AMOUNT_REQUEST = 'WITHDRAW_AMOUNT_REQUEST';

export const WITHDRAW_AMOUNT_SUCCESS = 'WITHDRAW_AMOUNT_SUCCESS';

export const WITHDRAW_AMOUNT_FAILED = 'WITHDRAW_AMOUNT_FAILED';

export const WITHDRAW_AMOUNT_ERROR = 'WITHDRAW_AMOUNT_ERROR';

export const SET_WITHDRAW_AMOUNT_LOADER = 'SET_WITHDRAW_AMOUNT_LOADER'