export const LEAGUE_LIST_REQUEST = 'LEAGUE_LIST_REQUEST';
export const LEAGUE_LIST_SUCCESS = 'LEAGUE_LIST_SUCCESS';
export const LEAGUE_LIST_FAILED =  'LEAGUE_LIST_FAILED';
export const LEAGUE_LIST_ERROR  =   'LEAGUE_LIST_ERROR';
export const SET_LEAGUE_LIST_LOADER =  'SET_LEAGUE_LIST_LOADER';


export const MATCH_LIST_REQUEST = 'MATCH_LIST_REQUEST';
export const MATCH_LIST_SUCCESS = 'MATCH_LIST_SUCCESS';
export const MATCH_LIST_FAILED =  'MATCH_LIST_FAILED';
export const MATCH_LIST_ERROR  =   'MATCH_LIST_ERROR';
export const SET_MATCH_LIST_LOADER =  'SET_MATCH_LIST_LOADER';