export const RANIKNG = 'RANIKNG'

export const RANIKNG_FAILURE = 'RANIKNG_FAILURE'

export const RANIKNG_REQUESTED = 'RANIKNG_REQUESTED'

export const RANIKNG_SUCCESS = 'RANIKNG_SUCCESS'

export const  SET_RANIKNG_ERROR = 'SET_RANIKNG_ERROR';

export const RULE_REGULATION_REQUEST = 'RULE_REGULATION_REQUEST';
export const RULE_REGULATION_SUCCESS = 'RULE_REGULATION_SUCCESS';
export const RULE_REGULATION_FAILED = 'RULE_REGULATION_FAILED';
export const  SET_RULE_REGULATION_ERROR = 'SET_RULE_REGULATION_ERROR';

export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILED = 'ADD_GROUP_FAILED';
export const  SET_ADD_GROUP_ERROR = 'SET_ADD_GROUP_ERROR';
export const ADD_GROUP_SHOW_LOADER='ADD_GROUP_SHOW_LOADER';

export const MY_GROUP_REQUEST = 'MY_GROUP_REQUEST';
export const MY_GROUP_SUCCESS = 'MY_GROUP_SUCCESS';
export const MY_GROUP_FAILED = 'MY_GROUP_FAILED';
export const  SET_MY_GROUP_ERROR = 'SET_MY_GROUP_ERROR';
export const My_GROUP_SHOW_LOADER='MY_GROUP_SHOW_LOADER';

export const ACCEPT_GROUP_REQUEST = 'ACCEPT_GROUP_REQUEST';
export const ACCEPT_GROUP_SUCCESS = 'ACCEPT_GROUP_SUCCESS';
export const ACCEPT_GROUP_FAILED = 'ACCEPT_GROUP_FAILED';
export const  SET_ACCEPT_MY_GROUP_ERROR = 'SET_ACCEPT_GROUP_ERROR';
export const ACCEPT_GROUP_SHOW_LOADER='ACCEPT_GROUP_SHOW_LOADER';

export const REJECT_GROUP_REQUEST = 'REJECT_GROUP_REQUEST';
export const REJECT_GROUP_SUCCESS = 'REJECT_GROUP_SUCCESS';
export const REJECT_GROUP_FAILED = 'REJECT_GROUP_FAILED';
export const  SET_REJECT_GROUP_ERROR = 'SET_REJECT_GROUP_ERROR';
export const REJECT_GROUP_SHOW_LOADER='REJECT_GROUP_SHOW_LOADER';