const Images = {
    backIcon: require('../assets/images/ico_back.png'),
    calender: require('../assets/images/calendar.png'),
    down: require('../assets/images/down.png'),
    search: require('../assets/images/ico_search.png'),
    check: require('../assets/images/check_blue.png'),
    line: require('../assets/images/Line2x.png'),
    fb: require('../assets/images/facebook.png'),
    mobile: require('../assets/images/mobile.png'),
    tabpic: require('../assets/images/img-1.png'),
    userPic: require('../assets/images/user_pic.png'),
    notifications: require('../assets/images/notifications.png'),
    rightBack: require('../assets/images/right_back.png'),
    fixcture: require('../assets/images/tb_fixtures.png'),
    predictWin: require('../assets/images/tb_predict&win.png'),
    user: require('../assets/images/tb_user.png'),
    account: require('../assets/images/account.png'),
    roundTick: require('../assets/images/radio_o.png'),
    roundBlueTick: require('../assets/images/radio_a.png'),
    headerBack: require('../assets/images/headerBack.png'),
    editIocn: require('../assets/images/edit.png'),
    trophy: require('../assets/images/trophy.png'),
    toggle: require('../assets/images/toggle.png'),
    inuser: require('../assets/images/inactive_user.png'),
    intophy: require('../assets/images/inactive_tophy.png'),
    inactive_tab: require('../assets/images/inactive_fixtures.png'),
    toggle_off: require('../assets/images/toggle_off.png'),
    add_group: require('../assets/images/add.png'),
    football: [
        require('../assets/images/football-1.jpg'),
        require('../assets/images/football-2.jpg'),
        require('../assets/images/football-3.jpg'),
        require('../assets/images/football-4.jpg'),
        require('../assets/images/football-5.jpg'),
        require('../assets/images/football-6.jpg'),
    ],
}

export default Images
