export const UserPredict = {
    name: 'UEFA Champions League',
    groups: ['Group A', 'Group B', 'Group C'],
    matchList: [
        {
            date: new Date(),
            matches: [
                {
                    groupName: 'Group A',
                    points: 200,
                    teamA: 'Denmark',
                    teamAScore: 2,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'finished',
                    type: 'Group',
                },
                {
                    groupName: 'Group B',
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'started',
                    type: 'Group',
                },
                {
                    groupName: 'Group D',
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'not-started',
                    time: new Date(),
                    type: 'Group',
                },
            ],
        },
        {
            date: new Date('26/05/2021'),
            matches: [
                {
                    points: 200,
                    teamA: 'Denmark',
                    teamAScore: 0,
                    teamAExtra: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    teamBExtra: 0,
                    status: 'not-started',
                    type: 'Quarter-Final',
                },
                {
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'not-started',
                    type: 'Quarter-Final',
                },
                {
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'not-started',
                    type: 'Quarter-Final',
                },
            ],
        },
    ],
}

export const ActualScore = {
    name: 'UEFA Champions League',
    groups: ['Group A', 'Group B', 'Group C'],
    matchList: [
        {
            date: new Date(),
            matches: [
                {
                    groupName: 'Group A',
                    points: 200,
                    teamA: 'Denmark',
                    teamAScore: 2,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'finished',
                    type: 'Group',
                },
                {
                    groupName: 'Group B',
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'started',
                    type: 'Group',
                },
                {
                    groupName: 'Group D',
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'not-started',
                    time: Date(),
                    startTime: Date(),
                    type: 'Group',
                },
            ],
        },
        {
            date: new Date('26/05/2021'),
            matches: [
                {
                    points: 200,
                    teamA: 'Denmark',
                    teamAScore: 0,
                    teamAExtra: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    teamBExtra: 0,
                    status: 'not-started',
                    type: 'Quarter-Final',
                    startTime: Date(),
                },
                {
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'not-started',
                    type: 'Quarter-Final',
                    startTime: Date(),
                },
                {
                    points: 0,
                    teamA: 'Clyde',
                    teamAScore: 0,
                    teamB: 'Finland',
                    teamBScore: 0,
                    status: 'not-started',
                    type: 'Quarter-Final',
                    startTime: Date(),
                },
            ],
        },
    ],
}
